#!/bin/sh

### Package: mix-alternatives-cython
### Version: v20210912.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLS
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# DEBIANREPO
if [ -z $DEBIANREPO ]; then
 DEBIANREPO=unstable
fi
echo "*** DEBIANREPO selected is $DEBIANREPO."

# PKGVER
if [ -z $PKGVER ]; then
 PKGVER=3
fi
echo "*** PKGVER selected is $PKGVER."

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin
 sudo apt-get -y -t $DEBIANREPO install cython$PKGVER
fi

## INSTALL
if [ $INSTALLDEPS = debian ]; then
 # PYTHON
 sudo rm /usr/bin/python
 sudo update-alternatives --install /usr/bin/cython cython /usr/bin/cython2 2
 sudo update-alternatives --install /usr/bin/cython cython /usr/bin/cython3 3
 # ALTERNATIVES
 sudo update-alternatives --config cython
fi

## EXIT
exit

## ENJOY
