#!/bin/sh

### Package: mix-install-wlgreet
### Version: v20210912.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: greetd

## OVERRIDES
# MIXTOOLS
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://git.sr.ht
GITREPO=~kennylevinsen
GITTREE=wlgreet
PKGDIR=$GITTREE\_$GITBRANCH

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git meson cargo
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
# Not using -d to retain cargo build directory for faster builds.
git clean -fx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## BUILD
cargo build --release

## INSTALL
sudo mkdir -p /usr/local/bin
sudo install -m 755 target/release/wlgreet /usr/local/bin/wlgreet
sudo mkdir -p /usr/local/etc/greetd
sudo install -m 644 -o greeter -g greeter $RESDIR/wlgreet/sway-config /usr/local/etc/greetd/wlgreet-sway-config
sudo install -m 644 -o greeter -g greeter $RESDIR/wlgreet/config.toml /usr/local/etc/greetd/wlgreet-config.toml

#sudo rm -f /usr/local/etc/greetd/config.toml
#sudo ln -s /usr/local/etc/greetd/wlgreet-config.toml /usr/local/etc/greetd/config.toml

## ALTERNATIVES
if [ $INSTALLDEPS = debian ]; then
 sudo update-alternatives --install /usr/local/etc/greetd/config.toml greetd-config /usr/local/etc/greetd/wlgreet-config.toml 11
 sudo update-alternatives --config greetd-config
fi

## EXIT
exit

## ENJOY
