#!/bin/sh

### Package: mix-install-x265
### Version: v20241118.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: svt-hevc

## OVERRIDES
# MIXTOOLS
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
fi

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi

# GITBRANCH
# Upstream branch is master
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# DESTDIR
if [ -z $DESTDIR ]; then
 DESTDIR=/usr/local
fi
echo "*** DESTDIR selected is $DESTDIR."

# CC
# Does not support ccache or gcc-14
CC="gcc-14"
echo "*** CC selected is $CC."

# CXX
# Does not support ccache or gcc-14
CXX="g++-14"
echo "*** CXX selected is $CXX."

## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://bitbucket.org
GITREPO=multicoreware
GITTREE=x265_git
PKGDIR=$GITTREE\_$GITBRANCH
MULTILIBDIR=`gcc -dumpmachine`

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y build-dep x265
 sudo apt-get -y install build-essential coreutils libc-bin git cmake
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard HEAD
git pull
git submodule update --init --depth=1

## CLEAN
rm -Rf tmpbuild

## PREP MULTILIB
mkdir tmpbuild
cd tmpbuild
mkdir 8bit 10bit 12bit

# Note -DENABLE_LIBVMAF=ON is currently broken

# 12BIT
cd 12bit
cmake ../../source -DENABLE_PIC=ON -DENABLE_ASSEMBLY=ON -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
-DHIGH_BIT_DEPTH=ON -DEXPORT_C_API=OFF -DENABLE_SHARED=OFF -DENABLE_CLI=OFF -DMAIN12=ON \
-DENABLE_HDR10_PLUS=ON
make -j `nproc`
cp libx265.a ../8bit/libx265_main12.a
cd ..

# 10BIT
cd 10bit
cmake ../../source -DENABLE_PIC=ON -DENABLE_ASSEMBLY=ON -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
-DHIGH_BIT_DEPTH=ON -DEXPORT_C_API=OFF -DENABLE_SHARED=OFF -DENABLE_CLI=OFF \
-DENABLE_HDR10_PLUS=ON
make -j `nproc`
cp libx265.a ../8bit/libx265_main10.a
cd ..

# 8BIT
cd 8bit
cmake ../../source -DENABLE_PIC=ON -DENABLE_ASSEMBLY=ON -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
-DEXTRA_LIB="x265_main10.a;x265_main12.a" -DEXTRA_LINK_FLAGS=-L. \
-DLINKED_10BIT=ON -DLINKED_12BIT=ON -DENABLE_SHARED=ON \
-DLIB_INSTALL_DIR=lib/$MULTILIBDIR \
-DENABLE_HDR10_PLUS=ON
make -j `nproc`

## INSTALL
sudo make install

sudo ldconfig

## EXIT
exit

## ENJOY
