#!/bin/sh

### Package: mix-install-guitarix
### Version: v20240811.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=$MIXTOOLSDIR/upstream
DESTDIR=/usr/local
MULTILIBDIR=`gcc -dumpmachine`
GITURL=https://github.com
GITREPO=brummer10
GITTREE=guitarix
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y build-dep guitarix
 sudo apt-get -y install build-essential coreutils libc-bin git meson \
 faust liblo-dev
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## BUILDDIR
cd trunk

## CONFIGURE
./waf configure --prefix=$DESTDIR --libdir=$DESTDIR/lib/$MULTILIBDIR \
--optimization --enable-lfs --enable-nls --shared-lib --lib-dev \
--includeresampler --includeconvolver --mod-lv2 \
--jack-session

## BUILD
./waf build

## INSTALL
sudo ./waf install
sudo ldconfig

## EXIT
exit

## ENJOY
