#!/bin/sh

### Package: mix-install-xrt-amdxdna
### Version: v20240620.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: xrt

## OVERRIDES
# MIXTOOLS
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
# Upstream branch is "master".
if [ -z $GITBRANCH ]; then
 GITBRANCH=main
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# CC
if [ -z $CC ]; then
 CC=ccache gcc-14
 export CC=$CC
fi
echo "*** CC selected is $CC."

# CXX
if [ -z $CXX ]; then
 CXX=ccache g++-14
 export CXX=$CXX
fi
echo "*** CXX selected is $CXX."

# BUILDCFLAGS
if [ -z $BUILDCFLAGS ]; then
 export CFLAGS="-O3 -march=native -B/usr/local/libexec/mold"
 export CXXFLAGS="${CFLAGS}"
fi
echo "*** BUILDCFLAGS selected is $CFLAGS."

## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=amd
GITTREE=xdna-driver
GITPRURL=https://patch-diff.githubusercontent.com
GITPRPATCH=$GITPRURL/raw/$GITREPO/$GITTREE/pull/$GITPR.patch
PKGDIR=$GITTREE\_$GITBRANCH

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git meson
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## CLEAN
rm -Rf build/Release/xrt_plugin*amdxdna.deb

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## GITPR
if [ $GITPR ]; then
 echo "*** GITPR selected is $GITPR."
 rm -f $DEVDIR/$GITTREE\_$GITPR.patch
 wget $GITPRPATCH -O $DEVDIR/$GITTREE\_$GITPR.patch
 patch -p1 < $DEVDIR/$GITTREE\_$GITPR.patch
fi

## PATCHES
# Fix broken check
#patch -p1 xrt/src/CMake/cpackLin.cmake < $RESDIR/xrt/xrt_disable_ubuntu_23.10_check.patch

## BUILD
cd build
./build.sh -release
./build.sh -example
./build.sh -package

## INSTALL
echo "Install xrt plugin file."
sudo dpkg -i Release/xrt_plugin*amdxdna.deb

## EXIT
exit

## ENJOY
