#!/bin/sh

### Package: mix-install-pbzx
### Version: v20201212.1200
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: xar

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi

## VARS
DEVDIR=$MIXTOOLSDIR/upstream
GITREPO=https://github.com/NiklasRosenstein
GITTREE=pbzx
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin wget patch \
 liblzma-dev libbz2-dev
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GET PATCH
[ -f pbzx_7.patch ] || wget https://patch-diff.githubusercontent.com/raw/NiklasRosenstein/pbzx/pull/7.patch -O pbzx_7.patch

## GIT
rm -Rf $PKGDIR
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard HEAD
git pull

## PATCH
patch -p1 < $DEVDIR/pbzx_7.patch

## BUILD
make

## INSTALL
sudo make install

## EXIT
exit

## ENJOY
