#!/bin/sh

### Package: mix-alternatives-python
### Version: v20210912.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLS
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# DEBIANREPO
if [ -z $DEBIANREPO ]; then
 DEBIANREPO=unstable
fi
echo "*** DEBIANREPO selected is $DEBIANREPO."

# PYTHONVER
if [ -z $PYTHONVER ]; then
 PYTHONVER=3
fi
echo "*** PYTHONVER selected is $PYTHONVER."

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin
 sudo apt-get -y -t $DEBIANREPO install python$PYTHONVER
fi

## INSTALL
if [ $INSTALLDEPS = debian ]; then
 # PYTHON
 sudo rm /usr/bin/python
 sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 2
 sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 3
 # ALTERNATIVES
 sudo update-alternatives --config python
fi

## EXIT
exit

## ENJOY
