#!/bin/sh

### Package: mix-install-blueman
### Version: v20241101.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=main
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# DESTDIR
if [ -z $DESTDIR ]; then
 DESTDIR=/usr
fi
echo "*** DESTDIR selected is $DESTDIR."

# SYSCONFDIR
if [ -z $SYSCONFDIR ]; then
 SYSCONFDIR=/etc
fi
echo "*** SYSCONFDIR selected is $SYSCONFDIR."

# LOCALSTATEDIR
if [ -z $LOCALSTATEDIR ]; then
 LOCALSTATEDIR=/var
fi
echo "*** LOCALSTATEDIR selected is $LOCALSTATEDIR."

## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=blueman-project
GITTREE=blueman
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
# sudo apt-get -y build-dep blueman
 sudo apt-get -y install build-essential coreutils libc-bin meson ninja-build \
 python3-caja nemo-python python3-nautilus cython3 python3
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## CLEAN
rm -Rf tmpbuild

## PATCH
#for file in $RESDIR/blueman/iptables*patch;do patch -p1 < $file;done

## CONFIGURE
PYTHON=/usr/bin/python3 CYTHONEXEC=/usr/bin/cython3 ./autogen.sh \
--prefix=$DESTDIR --libdir=$DESTDIR/lib/$MULTILIBDIR \
--exec-prefix=$DESTDIR --sysconfdir=$SYSCONFDIR --localstatedir=$LOCALSTATEDIR \
--enable-shared --enable-polkit --enable-caja-sendto --enable-nemo-sendto --enable-nautilus-sendto \
--enable-thunar-sendto --enable-settings-integration --enable-pulseaudio

#--disable-runtime-deps-check
#--with-dhcp-config=/etc/dhcp/dhcpd.conf --with-systemdsystemunitdir=/lib/systemd/system \


## BUILD
make -j `nproc`

## INSTALL
sudo make install
#sudo install -m 644 $RESDIR/blueman/blueman.rules /usr/share/polkit-1/rules.d/
#sudo install -m 644 $RESDIR/blueman/org.blueman.pkla /var/lib/polkit-1/localauthority/10-vendor.d/
sudo ldconfig

## EXIT
exit

## ENJOY
