#!/bin/sh

### Package: mix-install-gcc
### Version: v20220122.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# DESTDIR
if [ -z $DESTDIR ]; then
 DESTDIR=/usr/local
fi
echo "*** DESTDIR selected is $DESTDIR."

# CFLAGS
#if [ -z $CFLAGSTEST ]; then
# CFLAGS="-O3 -march=native -B/usr/local/libexec/mold -Wno-maybe-uninitialized"
# CXXFLAGS="$CFLAGS"
#fi
#echo "*** CFLAGS selected is $CFLAGS."

## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=/tmp/mix-tools
GITURL=https://gcc.gnu.org/git
GITREPO=gcc
GITTREE=gcc
PKGDIR=$GITTREE\_$GITBRANCH
MULTILIBDIR=`gcc -dumpmachine`

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git make cmake
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## CLEAN
sudo rm -Rf $PKGDIR/tmpbuild

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## CONFIGURE
./configure --prefix=$DESTDIR --libdir=$DESTDIR/lib/$MULTILIBDIR \
--enable-shared --enable-threads=posix --enable-clocale=gnu --enable-languages="c,c++,fortran" \
--enable--__cxa_atexit --enable-checking=release --enable-lto --enable-multilib \
--enable-plugin --disable-bootstrap \
--disable-libssp --disable-libstdcxx-pch --disable-werror
# \
#--enable-libada --enable-libssp --enable-lto --enable-shared --with-system-zlib
#--enable-languages=all

##--with-tune=native

## BUILD
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## EXIT
exit

## ENJOY
