#!/bin/sh

### Package: mix-install-obs-studio
### Version: v20220516.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR"

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS"

# GITBRANCH
# Upstream is master
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH"

# BROWSER
if [ -z $BROWSER ]; then
 BROWSER=no
fi
echo "*** BROWSER selected is $BROWSER"

if [ $BROWSER = yes ]; then
 BROWSERBUILD = -DBUILD_BROWSER=1 -DENABLE_BROWSER=1 -DCEF_ROOT_DIR="../../cef_binary_4280_linux64"
fi

## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=obsproject
GITTREE=obs-studio
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git cmake \
 qtbase5-private-dev libavdevice-dev libavfilter-dev libjansson-dev \
 libmbedtls-dev libpostproc-dev libpython3-dev libpython3.9-dev \
 libqt5svg5-dev libqt5x11extras5-dev libsimde-dev libspeex-dev libspeexdsp-dev \
 libvlc-dev libx264-dev libxcb-xinerama0-dev swig swig4.0 qtwayland5 dbus-x11 \
 libpci-dev
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## CEF
if [ $BROWSER = yes ]; then
 [ -d cef_binary_4280_linux64 ] || wget https://cdn-fastly.obsproject.com/downloads/cef_binary_4280_linux64.tar.bz2
 tar -xjf ./cef_binary_4280_linux64.tar.bz2
fi

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## CLEAN
rm -Rf tmpbuild

## PATCH
for patch in $PR; do
 [ -f $DEVDIR/PKGDIR\_$PR.patch ] || rm -f $DEVDIR/$PKGDIR\_$PR.patch
 wget https://patch-diff.githubusercontent.com/raw/$GITREPO/$GITTREE/pull/$PR.patch -O $DEVDIR/$PKGDIR\_$PR.patch
 git apply $DEVDIR/$PKGDIR\_$PR.patch
done

## CONFIGURE
mkdir tmpbuild
cd tmpbuild
cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DOBS_LIBRARY_DESTINATION=lib/x86_64-linux-gnu -DOBS_MULTIARCH_SUFFIX=/x86_64-linux-gnu \
-DDISABLE_UPDATE_MODULE=TRUE -DUNIX_STRUCTURE=1 -DCMAKE_BUILD_TYPE=release -DENABLE_PIPEWIRE=1 -DENABLE_BROWSER=0 -DBUILD_BROWSER=0 \
-DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache $BROWSERBUILD ..

## BUILD
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## EXIT
exit

## ENJOY
