#!/bin/sh

### Package: mix-install-resources
### Version: v20241101.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=main
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# GITPR
if [ -z $GITPR ]; then
 GITPR=none
fi
echo "*** GITPR selected is $GITPR."

# DESTDIR
if [ -z $DESTDIR ]; then
 DESTDIR=/usr/local
fi
echo "*** DESTDIR selected is $DESTDIR."

## VARS
DEVDIR=$MIXTOOLSDIR/upstream
RESDIR=$MIXTOOLSDIR/resources
GITURL=https://github.com
GITREPO=nokyan
GITTREE=resources
PKGDIR=$GITTREE\_$GITBRANCH
GITPRURL=$GITURL
GITPRPATCH=$GITPRURL/$GITREPO/$GITTREE/-/merge_requests/$GITPR.patch
MULTILIBDIR=`gcc -dumpmachine`

## INSTALLDEPS
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
sudo rm -Rf tmpbuild
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## GITPR
if [ $GITPR != none ]; then
 rm -f $DEVDIR/$GITTREE\_$GITPR.patch
 wget $GITPRPATCH -O $DEVDIR/$GITTREE\_$GITPR.patch
 patch -p1 < $DEVDIR/$GITTREE\_$GITPR.patch
fi

## CONFIGURE
meson setup tmpbuild --prefix=$DESTDIR --libdir=$DESTDIR/lib/$MULTILIBDIR --buildtype=release

## BUILD
ninja -C tmpbuild

## INSTALL
ninja -C tmpbuild install
sudo ldconfig

## EXIT
exit

# ENJOY
