#!/bin/sh

### Package: mix-install-xfce-thunar-plugins
### Version: v20241118.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: xfce-core

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR"

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS"

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH"

## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://gitlab.xfce.org
GITREPO=thunar-plugins

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y build-dep thunar-archive-plugin thunar-media-tags-plugin thunar-vcs-plugin
 sudo apt-get -y install build-essential coreutils libc-bin git
fi

## PREP
set -e
mkdir -p $DEVDIR/xfce/$GITREPO
cd $DEVDIR/xfce/$GITREPO

## LOG
LOG=$DEVDIR/xfce/$GITREPO.log
echo start > $LOG

## GIT
for GITTREE in thunar-archive-plugin thunar-media-tags-plugin thunar-shares-plugin thunar-vcs-plugin; do
 PKGDIR=$GITTREE\_$GITBRANCH
 echo $PKGDIR >> $LOG
 [ -d $PKGDIR ] || git clone --depth=1 --recursive $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
 cd $PKGDIR
 git clean -f
 git reset --hard
 git pull
 git submodule update --init --recursive --depth=1

 ## CLEAN
 [ ! -f Makefile ] || make clean

 ## CONFIGURE
 if [ -f autogen.sh ]; then
  ./autogen.sh
 fi
 ./configure --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu --enable-shared --disable-debug \
 --with-pic --enable-maintainer-mode

 ## BUILD
 make -j `nproc`

 ## INSTALL
 sudo make install
 sudo ldconfig
 echo done >> $LOG

 ## DONE
 cd $DEVDIR/xfce/$GITREPO
 done

## EXIT
exit

## ENJOY
