#!/bin/sh

### Package: mix-install-bluez
### Version: v20241101.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
# Upstream branch is master
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# DESTDIR
if [ -z $DESTDIR ]; then
 DESTDIR=/usr
fi
echo "*** DESTDIR selected is $DESTDIR."

# SYSCONFDIR
if [ -z $SYSCONFDIR ]; then
 SYSCONFDIR=/etc
fi
echo "*** SYSCONFDIR selected is $SYSCONFDIR."

# LOCALSTATEDIR
if [ -z $LOCALSTATEDIR ]; then
 LOCALSTATEDIR=/var
fi
echo "*** LOCALSTATEDIR selected is $LOCALSTATEDIR."

## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=bluez
GITTREE=bluez
PKGDIR=$GITTREE\_$GITBRANCH
MULTILIBDIR=`gcc -dumpmachine`

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
# sudo apt-get -y build-dep bluez
 sudo apt-get -y build-dep bluez
 sudo apt-get -y install build-essential coreutils libc-bin make
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## CONFIGURE
./bootstrap
./configure --prefix=$DESTDIR --libdir=$DESTDIR/lib/$MULTILIBDIR \
--exec-prefix=$DESTIDR --sysconfdir=/etc --localstatedir=/var \
--enable-threads --enable-library --enable-test --enable-nfc --enable-sap --enable-a2dp \
--enable-avrcp --enable-network --enable-hid --enable-hog --enable-health --enable-bap --enable-bass \
--enable-mcp --enable-ccp --enable-vcp --enable-micp --enable-csip --enable-asha \
--enable-tools --enable-monitor --enable-udev --enable-cups --enable-mesh --enable-midi \
--enable-obex --enable-btpclient --enable-external-ell --enable-client --enable-systemd \
--enable-datafiles --enable-manpages --enable-testing --enable-experimental --enable-deprecated \
--enable-sixaxis --enable-hid2hci --enable-logger --enable-admin

## BUILD
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## RESTART
sudo systemctl daemon-reload
sudo systemctl stop bluetooth bluetooth-logger bluetooth-mesh
sudo systemctl disable bluetooth bluetooth-logger bluetooth-mesh
sudo systemctl enable bluetooth bluetooth-logger bluetooth-mesh
sudo systemctl start bluetooth bluetooth-logger bluetooth-mesh
sudo systemctl daemon-reload

## EXIT
exit

## ENJOY
