#!/bin/sh

### Package: mix-install-wf-recorder
### Version: v20240504.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# GITPR
if [ -z $GITPR ]; then
 GITPR=none
fi
echo "*** GITPR selected is $GITPR."


## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=ammen99
GITTREE=wf-recorder
PKGDIR=$GITTREE\_$GITBRANCH
GITPRURL=https://patch-diff.githubusercontent.com/raw
GITPRPATCH=$GITPRURL/$GITREPO/$GITTREE/pull/$GITPR.patch

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git meson make
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## GITPR
if [ $GITPR != none ]; then
 rm -f $DEVDIR/$GITTREE\_$GITPR.patch
 wget $GITPRPATCH -O $DEVDIR/$GITTREE\_$GITPR.patch
 patch -p1 < $DEVDIR/$GITTREE\_$GITPR.patch
fi

## CONFIGURE
meson tmpbuild --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu --buildtype=release

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
exit

## ENJOY
