#!/bin/sh

### Package: mix-install-cpupower
### Version: v20241101.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# DESTDIR
if [ -z $DESTDIR ]; then
 DESTDIR=/usr
fi
echo "*** DESTDIR selected is $DESTDIR."

# PKGVER
if [ -z $PKGVER ]; then
 PKGVER=6.12-rc6
fi
echo "*** PKGVER selected is $PKGVER."

## VARS
DEVDIR=/tmp/mix-tools
MULTILIBDIR=`gcc -dumpmachine`
SBINDIR=$DESTDIR/bin
LIBDIR=$DESTDIR/lib/$MULTILIBDIR
MANDIR=$DESTDIR/share/man
DOCDIR=$DESTDIR/share/doc/cpupower
INCLUDEDIR=$DESTDIR/include

## INSTALLDEPS
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git \
 libpci-dev
fi

## INSTALL
cd $DEVDIR/linux-$PKGVER/tools/power/cpupower
sudo make sbindir=$SBINDIR \
libdir=$LIBDIR \
mandir=$MANDIR \
docdir=$DOCDIR \
includedir=$INCLUDEDIR \
install install-man

## EXIT
exit

## ENJOY
