#!/bin/sh

### Package: mix-install-pipewire
### Version: v20241101.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: libcamera

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# DESTDIR
# Note: default location is /usr!
if [ -z $DESTDIR ]; then
 DESTDIR=/usr
fi
echo "*** DESTDIR selected is $DESTDIR."

## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://gitlab.freedesktop.org
GITREPO=pipewire
GITTREE=pipewire
PKGDIR=$GITTREE\_$GITBRANCH
MULTILIBDIR=`gcc -dumpmachine`

## INSTALLDEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y build-dep pipewire libfdk-aac-dev+
 sudo apt-get -y install build-essential coreutils libc-bin git meson \
 libsdl2-dev libjack-jackd2-dev \
 libldacbt-enc-dev libldacbt-abr-dev libopenaptx-dev libfdk-aac-dev \
 libavcodec-dev libsystemd-dev libsndfile-dev libusb-dev libavahi-client-dev \
 libcap-dev libgstreamer1.0-dev \
 docutils-common gir1.2-gst-plugins-base-1.0 libgstreamer-gl1.0-0 \
 libgstreamer-plugins-base1.0-dev liborc-0.4-dev liborc-0.4-dev-bin \
 libsbc-dev libsbc1 libusb-1.0-0-dev libv4l-0 libv4l-dev libv4l2rds0 \
 libv4lconvert0 libwebrtc-audio-processing-dev libx11-xcb-dev \
 python3-docutils python3-roman jackd2 libopenal-dev \
 libcamera-dev libvulkan-dev openal-tools
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## CLEAN
sudo rm -Rf $PKGDIR/tmpbuild

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard HEAD
git pull
git submodule update --init --recursive --depth=1

## CONFIGURE
meson tmpbuild --prefix=$DESTDIR --libdir=$DESTDIR/lib/$MULTILIBDIR --buildtype=release \
-Ddocs=disabled -Dman=enabled -Dgstreamer=enabled -Dgstreamer-device-provider=enabled \
-Dsystemd=enabled -Dsystemd-system-service=enabled -Dsystemd-user-service=enabled \
-Dpipewire-alsa=enabled -Dpipewire-jack=enabled -Dpipewire-v4l2=enabled -Djack-devel=true \
-Dspa-plugins=enabled -Dalsa=enabled -Daudiomixer=enabled \
-Daudioconvert=enabled -Dbluez5=enabled -Dbluez5-backend-hsp-native=enabled \
-Dbluez5-backend-hfp-native=enabled -Dbluez5-backend-native-mm=enabled -Dbluez5-backend-ofono=enabled -Dbluez5-backend-hsphfpd=enabled \
-Dbluez5-codec-aptx=enabled -Dbluez5-codec-ldac=enabled -Dbluez5-codec-aac=enabled \
-Dbluez5-codec-lc3plus=disabled -Dbluez5-codec-opus=enabled -Dbluez5-codec-lc3=disabled -Dcontrol=enabled \
-Daudiotestsrc=enabled -Dffmpeg=enabled -Djack=enabled -Dsupport=enabled -Devl=disabled \
-Dv4l2=enabled -Ddbus=enabled -Dlibcamera=enabled -Dvideoconvert=enabled -Dvideotestsrc=enabled \
-Dvolume=enabled -Dvulkan=enabled -Dpw-cat=enabled -Dpw-cat-ffmpeg=enabled -Dudev=enabled -Dsdl2=enabled -Dsndfile=enabled \
-Dlibmysofa=enabled -Dlibpulse=enabled -Droc=enabled -Davahi=enabled -Decho-cancel-webrtc=enabled -Dlibusb=enabled \
-Draop=enabled -Dlv2=enabled -Dx11=enabled -Dx11-xfixes=enabled -Dlibcanberra=enabled \
-Dlegacy-rtkit=true -Davb=enabled -Dflatpak=enabled -Dreadline=enabled -Dgsettings=enabled \
-Dcompress-offload=enabled -Dpam-defaults-install=false -Dopus=enabled -Dlibffado=enabled \
-Dlogind=enabled -Dlogind-provider=libsystemd -Dgsettings-pulse-schema=enabled -Dsnap=enabled

# docs disabled to test
# evl disabled to test
# lc3plus and lc3 disabled to test

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## SYSTEM CONFIG
#[ ! -f /usr/local/share/pipewire/media-session.d/with-jack ] && \
# sudo touch /usr/local/share/pipewire/media-session.d/with-jack
#[ ! -f /usr/local/share/pipewire/media-session.d/with-alsa ] && \
# sudo touch /usr/local/share/pipewire/media-session.d/with-alsa
#[ ! -L /etc/alsa/conf.d/99-pipewire-default.conf ] && \
# sudo ln -s /usr/local/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d/99-pipewire-default.conf

## USER CONFIG
systemctl --user stop pulseaudio
systemctl --user disable pulseaudio
systemctl --user mask pulseaudio
systemctl --user daemon-reload
systemctl --user enable --now pipewire pipewire-pulse
systemctl --user stop --now pipewire pipewire-pulse
systemctl --user start --now pipewire pipewire-pulse
systemctl --user daemon-reload

## EXIT
exit

## ENJOY
