#!/bin/sh

### Package: mix-install-fontawesome
### Version: v20210912.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## VARS
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=fortawesome
GITTREE=font-awesome
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS ]; then
 if [ $INSTALLDEPS = debian ]; then
  sudo apt-get -y install coreutils git
 fi
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## INSTALL
sudo mkdir -p /usr/local/share/fonts/TTF
sudo mkdir -p /usr/local/share/fonts/OTF
sudo install -Dm644 webfonts/*.ttf /usr/local/share/fonts/TTF/
sudo install -Dm644 otfs/*.otf /usr/local/share/fonts/OTF/

## EXIT
exit

## ENJOY
