#!/bin/sh

### Package: mix-install-lsmash-works
### Version: v20241101.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLS
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
fi

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# DESTDIR
if [ -z $DESTDIR ]; then
 DESTDIR=/usr/local
fi
echo "*** DESTDIR selected is $DESTDIR."

# FFMPEGROOTDIR
if [ -z $FFMPEGROOTDIR ]; then
 FFMPEGROOTDIR=/usr/local/ffmpeg-lsmashsource
fi
echo "*** FFMPEGROOTDIR selected is $FFMPEGROOTDIR."


## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=HomeOfAviSynthPlusEvolution
GITTREE=l-smash-works
PKGDIR=$GITTREE\_$GITBRANCH
MULTILIBDIR=`gcc -dumpmachine`

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init

## CONFIGURE
cd VapourSynth
meson setup tmpbuild --prefix=$DESTDIR --libdir=$DESTDIR/lib/$MULTILIBDIR --buildtype=release

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
exit

## ENJOY

## PATCH
#cp FindFFMPEG.cmake FindFFMPEG.cmake.orig
#patch -p1 < $DEVDIR/FindFFMPEG.cmake.diff FindFFMPEG.cmake

cmake -DCMAKE_INSTALL_PREFIX=$DESTDIR -DCMAKE_INSTALL_LIBDIR=$DESTDIR/lib/$MULTILIBDIR \
-DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
-DUSE_CCACHE=ON -B ./tmpbuild \
-DFFMPEG_INCLUDE_DIRS=$FFMPEGROOTDIR/include -DFFMPEG_LIBRARIES=$FFMPEGROOTDIR/lib/$MULTILIBDIR \
-DFFMPEG_avcodec_LIBRARY=$FFMPEGROOTDIR/lib/$MULTILIBDIR/libavcodec.so \
-DFFMPEG_avcodec_INCLUDE_DIRS=$FFMPEGROOTDIR/include/libavcodec \
-DFFMPEG_avdevice_LIBRARY=$FFMPEGROOTDIR/lib/$MULTILIBDIR/libavdevice.so \
-DFFMPEG_avdevice_INCLUDE_DIRS=$FFMPEGROOTDIR/include/libavdevice \
-DFFMPEG_avfilter_LIBRARY=$FFMPEGROOTDIR/lib/$MULTILIBDIR/libavfilter.so \
-DFFMPEG_avfilter_INCLUDE_DIRS=$FFMPEGROOTDIR/include/libavfilter \
-DFFMPEG_avformat_LIBRARY=$FFMPEGROOTDIR/lib/$MULTILIBDIR/libavformat.so \
-DFFMPEG_avformat_INCLUDE_DIRS=$FFMPEGROOTDIR/include/libavformat \
-DFFMPEG_avutil_LIBRARY=$FFMPEGROOTDIR/lib/$MULTILIBDIR/libavutil.so \
-DFFMPEG_avutil_INCLUDE_DIRS=$FFMPEGROOTDIR/include/libavutil
cmake --build tmpbuild --config Release -j `nproc`
sudo cmake --install ./tmpbuild
