#!/bin/sh

### Package: mix-install-desktop
### Version: v20201212.1200
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: linux

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi

## VARS
INSTALL="sudo apt-get -y install"

## OVERRIDES
# Provide stable, testing, or unstable.
if [ $DEBRELEASE ]; then
 if [ $DEBRELEASE = stable ]; then
  echo "\n*** DEBRELEASE selected is stable.\n"
 elif [ $DEBRELEASE = testing ]; then
  echo "\n*** DEBRELEASE selected is testing.\n"
 elif [ $DEBRELEASE = unstable ]; then
  echo "\n*** DEBRELEASE selected is unstable.\n"
 else
  echo "\n*** DEBRELEASE must be passed on commandline as stable, testing, or unstable.\n"
  exit
 fi
fi
if [ -z $DEBRELEASE ]; then
 echo "\n*** DEBRELEASE must be passed on commandline as stable, testing, or unstable.\n"
 exit
fi

# Override yes with no to NOT install apt sources.list and preferences.
if [ -z $APTSOURCES ]; then
 APTSOURCES=yes
fi
echo "\n*** APTSOURCES selected is $APTSOURCES.\n"

# Override yes with no to NOT use deb-multimedia.org packages.
if [ -z $DEBMULTIMEDIA ]; then
 DEBMULTIMEDIA=yes
fi
echo "\n*** DEBMULTIMEDIA selected is $DEBMULTIMEDIA.\n"

# Override no with yes to install sway, waybar and bash configs.
if [ -z $USERCONFIGS ]; then
 USERCONFIGS=no
fi
echo "\n*** USERCONFIGS selected is $USERCONFIGS.\n"

# Override yes with no to NOT install sway desktop.
if [ -z $BASE ]; then
 BASE=yes
fi
echo "\n*** BASE selected is $BASE.\n"

# Override sway with none for no desktop.
if [ -z $DESKTOP ]; then
 DESKTOP=sway
fi
echo "\n*** DESKTOP selected is $DESKTOP.\n"

# Override no with yes to install hwaccel.
if [ -z $HWACCEL ]; then
 HWACCEL=no
fi
echo "\n*** HWACCEL selected is $HWACCEL.\n"

# Override no with yes to install media.
if [ -z $MEDIA ]; then
 MEDIA=no
fi
echo "\n*** MEDIA selected is $MEDIA.\n"

# Override no with yes to install wayland.
if [ -z $WAYLAND ]; then
 WAYLAND=no
fi
echo "\n*** WAYLAND selected is $WAYLAND.\n"

## CONTINUE
echo "\n*** Continue to install the above configurations? \n"
read -p "Yes or No:  " CONTINUE
case $CONTINUE in
 [Yy]* ) echo "\n*** YES selected. Continuing.\n" ;;
 [Nn]* ) echo "\n*** NO selected. Exiting.\n" && exit ;;
 * ) echo "\n***YES or NO not selected. Exiting.\n" && exit ;;
esac

## APTSOURCES
if [ $APTSOURCES = yes ]; then
 sudo install -Dm644 resources/apt/preferences.$DEBRELEASE /etc/apt/preferences
 sudo install -Dm644 resources/apt/sources.list.$DEBRELEASE /etc/apt/sources.list
fi

## DEBIAN MULTIMEDIA
if [ $DEBMULTIMEDIA = yes ]; then
 sudo mkdir -p /etc/apt/sources.list.d/
 sudo install -Dm644 resources/apt/deb-multimedia.list.$DEBRELEASE /etc/apt/sources.list.d/deb-multimedia.list
 sudo apt-get -y update -oAcquire::AllowInsecureRepositories=true
 sudo apt-get -y install deb-multimedia-keyring --allow-unauthenticated
 sudo apt-get -y update
 sudo apt-get -y dist-upgrade
fi

## USERCONFIGS
if [ $USERCONFIGS = yes ]; then
 mkdir -p ~/.config/sway
 mkdir -p ~/.config/waybar
 cp resources/sway/config ~/.config/sway/config
 cp resources/waybar/config ~/.config/waybar/config
 cp resources/bash/bash_profile ~/.bash_profile
fi

## BASE
if [ $BASE = yes ]; then
 # system
 $INSTALL udev p7zip-full lrzip zip zstd bzip2 hdparm hddtemp smartmontools curl
 # build
 $INSTALL coreutils build-essential bison flex make cmake meson git wget patch make autoconf automake
 # fonts
 $INSTALL fonts-dejavu fonts-freefont-ttf fonts-liberation fonts-roboto ttf-bitstream-vera
 # x
 $INSTALL xserver-xorg
 # power
 $INSTALL upower linux-cpupower brightnessctl brightness-udev light
 # audio
 $INSTALL pulseaudio pulseaudio-utils pulseaudio-module-bluetooth pavucontrol alsa-utils alsa-tools
 # networking
 $INSTALL bluez bluez-obexd bluetooth blueman network-manager
 # internet
 $INSTALL chromium firefox
 # graphics
 $INSTALL inkscape gimp
 # media
 $INSTALL vlc mpv ffmpeg audacity mediainfo mediainfo-gui
 # office
 $INSTALL libreoffice
 # remote
 $INSTALL rdesktop
fi

## DESKTOP
if [ $DESKTOP = sway ]; then
  # wayland
 $INSTALL xwayland grim slurp imv mako-notifier wl-clipboard
 # files
 $INSTALL thunar gvfs gvfs-backends gvfs-bin gvfs-fuse fuse3 mousepad
 # misc
 $INSTALL pasystray network-manager-gnome gftp gftp-gtk
fi

## HWACCEL
if [ $HWACCEL = yes ]; then
 # hwaccel
 INSTALLDEPS=debian ./mix-install-mesa
 INSTALLDEPS=debian ./mix-install-libva
 INSTALLDEPS=debian ./mix-install-libva-utils
 INSTALLDEPS=debian ./mix-install-alacritty
 INSTALLDEPS=debian ./mix-install-intel-gmmlib
 INSTALLDEPS=debian ./mix-install-intel-hybrid-driver
 INSTALLDEPS=debian ./mix-install-intel-media-driver
 INSTALLDEPS=debian ./mix-install-intel-vaapi-driver
fi

## MEDIA
if [ $MEDIA = yes ]; then
 # media
 INSTALLDEPS=debian ./mix-install-libcamera
 INSTALLDEPS=debian ./mix-install-pipewire
fi

## WAYLAND
if [ $WAYLAND = yes ]; then
 # wayland
 INSTALLDEPS=debian ./mix-install-xdg-desktop-portal
 INSTALLDEPS=debian ./mix-install-xdg-desktop-portal-wlr
 INSTALLDEPS=debian ./mix-install-fontawesome
 INSTALLDEPS=debian ./mix-install-sway
 INSTALLDEPS=debian ./mix-install-dmenu-wayland
 INSTALLDEPS=debian ./mix-install-waybar
 INSTALLDEPS=debian ./mix-install-wdisplays
 INSTALLDEPS=debian ./mix-install-wlogout
fi

## EXIT
exit

## ENJOY
