#!/bin/sh

### Package: mix-install-libbdplus
### Version: v20240504.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# GITPR
if [ -z $GITPR ]; then
 GITPR=none
fi
echo "*** GITPR selected is $GITPR."

## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://code.videolan.org
GITREPO=videolan
GITTREE=libbdplus
PKGDIR=$GITTREE\_$GITBRANCH
#GITPRURL=$GITURL
#https://code.videolan.org/videolan/libbdplus/-/merge_requests/10.patch
GITPRPATCH=$GITURL/$GITREPO/$GITTREE/-/merge_requests/$GITPR.patch

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git make
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## CLEAN
sudo rm -Rf $PKGDIR/tmpbuild

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## GITPR
if [ $GITPR != none ]; then
 rm -f $DEVDIR/$GITTREE\_$GITPR.patch
 wget $GITPRPATCH -O $DEVDIR/$GITTREE\_$GITPR.patch
 patch -p1 < $DEVDIR/$GITTREE\_$GITPR.patch
fi

## PATCH
patch -p1 < $RESDIR/libbdplus/libbdplus-gpg-error.patch

## CONFIGURE
autoreconf -vifs
./configure --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu
#meson tmpbuild --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu \
#--buildtype=release

## BUILD
make -j `nproc`
#ninja -C tmpbuild

## INSTALL
sudo make install
#sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
exit

## ENJOY
