#!/bin/sh

### Package: mix-install-gtkgreet
### Version: v20210912.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: gtreetd

## OVERRIDES
# MIXTOOLS
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://git.sr.ht
GITREPO=~kennylevinsen
GITTREE=gtkgreet
PKGDIR=$GITTREE\_$GITBRANCH

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git meson \
 pkg-config libgtk-layer-shell-dev libjson-c-dev scdoc
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## CLEAN
sudo rm -Rf $PKGDIR/tmpbuild

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## CONFIGURE
meson tmpbuild --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu --buildtype=release

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo mkdir -p /usr/local/etc/greetd
sudo install -m 644 -o greeter -g greeter $RESDIR/gtkgreet/sway-config /usr/local/etc/greetd/gtkgreet-sway-config
sudo install -m 644 -o greeter -g greeter $RESDIR/gtkgreet/config.toml /usr/local/etc/greetd/gtkgreet-config.toml
sudo install -m 644 -o greeter -g greeter $RESDIR/gtkgreet/gtkgreet.css /usr/local/etc/greetd/gtkgreet.css
#sudo rm -f /usr/local/etc/greetd/config.toml
#sudo ln -s /usr/local/etc/greetd/gtkgreet-config.toml /usr/local/etc/greetd/config.toml
sudo ldconfig

## ALTERNATIVES
if [ $INSTALLDEPS = debian ]; then
 sudo update-alternatives --install /usr/local/etc/greetd/config.toml greetd-config /usr/local/etc/greetd/gtkgreet-config.toml 12
 sudo update-alternatives --config greetd-config
fi

## EXIT
exit

## ENJOY
