#!/bin/sh

### Package: nix-install-fontawesome
### Version: v20201212.1200
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi

## VARS
DEVDIR=$NIXTOOLSDIR/upstream
GITREPO=https://github.com/fortawesome
GITTREE=font-awesome
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS ]; then
 if [ $INSTALLDEPS = debian ]; then
  sudo apt-get -y install coreutils git
 fi
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard
git pull

## INSTALL
sudo mkdir -p /usr/local/share/fonts/TTF
sudo mkdir -p /usr/local/share/fonts/OTF
sudo install -Dm644 webfonts/*.ttf /usr/local/share/fonts/TTF/
sudo install -Dm644 otfs/*.otf /usr/local/share/fonts/OTF/
echo "\n*** Install complete.\n"

## EXIT
exit

## ENJOY
