#!/bin/sh

### Package: nix-install-rustup
### Version: v20240611.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR.\n"

## OVERRIDES
# Override debian.
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS.\n"

echo "*** Uninstalling rustc, cargo, and rustup if installed."
## DEBIAN OPTIONS LOOP
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y --purge remove rustc cargo rustup
 sudo apt-get -y autoremove
fi

## INSTALL
echo "*** Installing rustup for user."
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# -s -- -q -y --default-toolchain stable

echo "*** Installing rustup for root."
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sudo sh
# -s -- -q -y --default-toolchain stable

## CONFIGURE
rustup toolchain install stable
rustup default stable
rustup component add rust-src

## EXIT
exit

## ENJOY
