#!/bin/sh

### Package: nix-install-sway
### Version: v20210813.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: wlroots

## OVERRIDES
# NIXTOOLS
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR.\n"

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS.\n"

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH.\n"

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=swaywm
GITTREE=sway
PKGDIR=$GITTREE\_$GITBRANCH

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y -t experimental build-dep sway
 sudo apt-get -y install build-essential coreutils libc-bin git meson \
 fish
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## CLEAN
rm -Rf tmpbuild

## CONFIGURE
meson tmpbuild --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu --buildtype=release \
-Dlibseat=true

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
[ -f /usr/local/bin/sway-run ] || sudo install -m 755 $RESDIR/sway/sway-run /usr/local/bin/sway-run
sudo ldconfig

## EXIT
exit

## ENJOY
