#!/bin/sh

### Package: nix-alternatives-llvm
### Version: v20210912.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLS
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# DEBIANREPO
if [ -z $DEBIANREPO ]; then
 DEBIANREPO=unstable
fi
echo "*** DEBIANREPO selected is $DEBIANREPO."

# LLVMVER
if [ -z $LLVMVER ]; then
 LLVMVER=13
fi
echo "*** LLVMVER selected is $LLVMVER."

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin
 sudo apt-get -y -t $DEBIANREPO install llvm llvm-$LLVMVER llvm-$LLVMVER-dev
fi

## INSTALL
if [ $INSTALLDEPS = debian ]; then
 # LLVM
 sudo rm /usr/bin/llvm-config
 sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-11 11
 sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-12 12
 sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-13 13
 sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-14 14

 # ALTERNATIVES
 sudo update-alternatives --config llvm-config
fi

## EXIT
exit

## ENJOY
