#!/bin/sh

### Package: nix-install-xfce-core
### Version: v20210627.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR"

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS"

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH"

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://gitlab.xfce.org
GITREPO=xfce

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 #sudo apt-get -y build-dep xfce4-dev-tools xfce4-settings exo garcon libxfce4ui libxfce4util thunar \
 #thunar-volman tumbler xfce4-appfinder xfce4-panel xfce4-power-manager xfce4-session xfconf xfdesktop4 xfwm4
 sudo apt-get -y install build-essential coreutils libc-bin git
fi

## PREP
set -e
mkdir -p $DEVDIR/xfce/$GITREPO
cd $DEVDIR/xfce/$GITREPO

## LOG
LOG=$DEVDIR/xfce/$GITREPO.log
echo start > $LOG

## GIT
for GITTREE in xfce4-dev-tools libxfce4util xfconf libxfce4ui garcon exo thunar xfce4-panel xfce4-settings \
xfce4-session xfdesktop xfwm4 xfce4-appfinder tumbler thunar-volman xfce4-power-manager; do
 PKGDIR=$GITTREE\_$GITBRANCH
 echo $PKGDIR >> $LOG
 [ -d $PKGDIR ] || git clone --depth=1 --recursive $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
 cd $PKGDIR
 git clean -f
 git reset --hard
 git pull
 git submodule update --init --recursive --depth=1

 ## CLEAN
 [ ! -f Makefile ] || make clean

 ## CONFIGURE
 [ -f autogen.sh ] && ./autogen.sh --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu --enable-shared --enable-debug --with-pic

 ## BUILD
 make -j `nproc`

 ## INSTALL
 sudo make install
 sudo ldconfig
 echo done >> $LOG

 ## DONE
 cd $DEVDIR/xfce/$GITREPO
 done

## UPDATE-ALTERNATIVES
if [ $INSTALLDEPS = debian ]; then
 sudo update-alternatives --install /usr/bin/x-window-manager x-window-manager /usr/local/bin/startxfce4 999
 sudo update-alternatives --config x-window-manager
fi

## EXIT
exit

## ENJOY
