#! /bin/sh

### Package: nix-install-task-ffmpeg
### Version: v20240728.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 export NIXTOOLSDIR=~/Development/XMIXAHLX/nix-tools
 export PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

# SVTAV1VER
# override with anything else to select official
if [ -z $SVTAV1VER ]; then
 SVTAV1VER=PSY
fi
echo "*** SVTAV1VER selected is $SVTAV1VER."

## INSTALL
nix-install-dav1d
nix-install-libdvbcsa
nix-install-libdca
nix-install-libmpeg2
nix-install-libbdplus
nix-install-libudfread
nix-install-liba52
nix-install-libaacs
nix-install-libbluray
nix-install-libdvdnav
nix-install-libdvdread
nix-install-libdvdcss
nix-install-lensfun
nix-install-vmaf
nix-install-svt-hevc
# SVTAV1VER
if [ $SVTAV1VER = PSY ];then
 nix-install-dovi
 nix-install-hdr10plus
 nix-install-svt-av1-psy
 else
 nix-install-svt-av1
fi
nix-install-x264
nix-install-x265
nix-install-ffmpeg

## EXIT
exit

## ENJOY
