#!/bin/sh

### Package: nix-install-cosmic-screenshot
### Version: v20241001.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLS
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
fi

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# DESTDIR
if [ -z $DESTDIR ]; then
 DESTDIR=/usr
fi
echo "*** DESTDIR selected is $DESTDIR."

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=pop-os
GITTREE=cosmic-screenshot
PKGDIR=$GITTREE\_$GITBRANCH
MULTILIBDIR=`gcc -dumpmachine`

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git \
 just libglvnd-dev libwayland-dev libseat-dev libxkbcommon-dev libinput-dev \
 udev dbus libdbus-1-dev libpam0g-dev libpixman-1-dev libssl-dev libflatpak-dev \
 libsystemd-dev libpulse-dev libexpat1-dev libfontconfig-dev \
 libfreetype-dev mold libgbm-dev libclang-dev libpipewire-0.3-dev
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init

## IGNORE RUST VERSION
rm -f rust-toolchain*

## BUILD
just build-release

## INSTALL
sudo just prefix="$DESTDIR" install

## EXIT
exit

## ENJOY
