#!/bin/sh

### Package: nix-alternatives-gcc
### Version: v20210813.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLS
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
fi

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi

# DEBIANREPO
if [ -z $DEBIANREPO ]; then
 DEBIANREPO=experimental
fi
echo "*** DEBIANREPO selected is $DEBIANREPO.\n"

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin
 sudo apt-get -y install -t $DEBIANREPO gcc gcc-10 gcc-11 g++ g++-10 g++-11
fi

## INSTALL
if [ $INSTALLDEPS = debian ]; then
 # GCC
 sudo rm /usr/bin/gcc
 sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
 sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11

 # G++
 sudo rm /usr/bin/g++
 sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
 sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 11

 # ALTERNATIVES
 sudo update-alternatives --config gcc
 sudo update-alternatives --config g++
fi

## EXIT
exit

## ENJOY
