#!/bin/sh

### Package: nix-install-xrt
### Version: v202406121.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: rapidjson

## OVERRIDES
# NIXTOOLS
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
# Upstream branch is "master".
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# CC
# gcc-14 is not yet supported
CC="ccache gcc-14"
CXX="ccache g++-14"
echo "*** CC selected is $CC."
echo "*** CXX selected is $CXX."

# GITBRANCH
# Upstream branch is "master".
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=xilinx
GITTREE=xrt
GITPRURL=https://patch-diff.githubusercontent.com
GITPRPATCH=$GITPRURL/raw/$GITREPO/$GITTREE/pull/$GITPR.patch
PKGDIR=$GITTREE\_$GITBRANCH

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git meson
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## CLEAN
rm -Rf Release/xrt*xrt.deb

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## GITPR
if [ $GITPR ]; then
 echo "*** GITPR selected is $GITPR."
 rm -f $DEVDIR/$GITTREE\_$GITPR.patch
 wget $GITPRPATCH -O $DEVDIR/$GITTREE\_$GITPR.patch
 patch -p1 < $DEVDIR/$GITTREE\_$GITPR.patch
fi

## PATCHES
# fix broken Ubuntu check
patch -p1 src/CMake/cpackLin.cmake < $RESDIR/xrt/xrt_disable_ubuntu_23.10_check.patch

## BUILD
cd build
./build.sh -opt -noert -noalveo

## INSTALL
echo "Install xrt*xrt.deb file from $RESDIR."
sudo dpkg -i Release/xrt*xrt.deb

## EXIT
exit

## ENJOY
