#!/bin/sh

### Package: nix-install-pbzx
### Version: v20200720.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: xar

## NIXTOOLS
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
fi

## VARS
DEVDIR=$NIXTOOLSDIR/upstream
GITREPO=https://github.com/NiklasRosenstein
GITTREE=pbzx
GITBRANCH=master
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS ]; then
 if [ $INSTALLDEPS = debian ]; then
  sudo apt-get -y install build-essential coreutils libc-bin wget patch \
  liblzma-dev libbz2-dev
 fi
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GET PATCH
[ -f pbzx_7.patch ] || wget https://patch-diff.githubusercontent.com/raw/NiklasRosenstein/pbzx/pull/7.patch -O pbzx_7.patch

## GIT
rm -Rf $PKGDIR
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard HEAD
git pull

## PATCH
patch -p1 < $DEVDIR/pbzx_7.patch

## BUILD
make

## INSTALL
sudo make install

## EXIT
exit

## ENJOY
