#! /bin/sh

### Package: nix-install-task-alsa
### Version: v20240811.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 export NIXTOOLSDIR=~/Development/XMIXAHLX/nix-tools
 export PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

## INSTALL
# NOTE: Default install location is usr/system. See fake-debian for management:
# https://github.com/xmixahlx/fake-debian
nix-install-alsa-lib
nix-install-alsa-utils
nix-install-alsa-ucm-conf
nix-install-alsa-tinycompress
nix-install-alsa-utils

## EXIT
exit

## ENJOY
