#!/bin/sh

### Package: nix-install-wayland-protocols
### Version: v20201212.1200
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: wayland

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITREPO=https://gitlab.freedesktop.org/wayland
GITTREE=wayland-protocols
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y build-dep wayland-protocols
 sudo apt-get -y install build-essential coreutils libc-bin git meson
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard
git pull

## CONFIGURE
./autogen.sh --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu/

## BUILD
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## EXIT
exit

## ENJOY
