#!/bin/sh

### Package: nix-install-lc3plus
### Version: v20220626.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=main
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
MULTILIBDIR=`gcc -dumpmachine`
DESTDIR=/usr/local
PKGDIR=lc3plus

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git meson
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## CLEAN
#sudo rm -Rf $PKGDIR/tmpbuild

## PREP
mkdir -p $PKGDIR
cd $PKGDIR
[ -f ts_103634v010301p0.zip ] || wget https://www.etsi.org/deliver/etsi_ts/103600_103699/103634/01.03.01_60/ts_103634v010301p0.zip
[ -d ETSI_Release ] || unzip ts_103634v010301p0.zip

## BUILD
cd ETSI_Release/LC3plus_ETSI_src_v172062927c2_20210930/src/floating_point
cp $RESDIR/lc3plus/CMakeLists.txt .
cp $RESDIR/lc3plus/LC3plus.pc.in .
mkdir -p tmpbuild
cd tmpbuild
cmake -DCMAKE_INSTALL_PREFIX:PATH=$DESTDIR ..
make

## INSTALL
sudo make install
sudo ldconfig

## EXIT
exit

## ENJOY
