#!/bin/sh

### Package: nix-install-xfce-apps
### Version: v20210627.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: xfce-core

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR"

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS"

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH"

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://gitlab.xfce.org
GITREPO=apps

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y build-dep gigolo mousepad parole ristretto xfburn xfce4-dict xfce4-notifyd \
 xfce4-screensaver xfce4-screenshooter xfce4-taskmanager xfce4-terminal
 sudo apt-get -y install build-essential coreutils libc-bin git\
 libkeybinder-3.0-dev libmpd-dev
fi

# build: catfish xfce4-panel-profiles
# missing: xfce4-mixer xfce4-panel-profiles xfce4-volumed-pulse xfdashboard xfmpc

## PREP
set -e
mkdir -p $DEVDIR/xfce/$GITREPO
cd $DEVDIR/xfce/$GITREPO

## GIT LOOP
for GITTREE in gigolo mousepad parole ristretto xfburn xfce4-dict xfce4-mixer xfce4-notifyd \
xfce4-screensaver xfce4-screenshooter xfce4-taskmanager xfce4-terminal xfce4-volumed-pulse \
xfdashboard xfmpc; do

 # VARS
 PKGDIR=$GITTREE\_$GITBRANCH

 # GIT
 [ -d $PKGDIR ] || git clone --depth=1 --recursive $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
 cd $PKGDIR
 git clean -f
 git reset --hard
 git pull
 git submodule update --init --recursive --depth=1

 ## CONFIGURE
 [ -f autogen.sh ] && ./autogen.sh --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu --enable-shared --enable-debug --with-pic

 ## BUILD
 make -j `nproc`

 ## INSTALL
 sudo make install
 sudo ldconfig

 ## XFCE4-SCREENSAVER INSTALL
 if [ $GITTREE = xfce4-screensaver ]; then
  [ -L /etc/pam.d/xfce4-screensaver ] || sudo ln -s /usr/local/etc/pam.d/xfce4-screensaver /etc/pam.d/xfce4-screensaver
 fi

 ## DONE
 cd $DEVDIR/xfce/$GITREPO
 done

## EXIT
exit

## ENJOY
