#!/bin/sh

### Package: nix-install-makemkv
### Version: v20230926.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# PKGVER
if [ -z $PKGVER ]; then
 PKGVER=1.16.5
fi
echo "*** PKGVER selected is $PKGVER."

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
MKVOSS=makemkv-oss-$PKGVER
MKVBIN=makemkv-bin-$PKGVER
MKVOSSFILE=$MKVOSS.tar.gz
MKVBINFILE=$MKVBIN.tar.gz
MKVURL=https://www.makemkv.com/download

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git make \
 libavutil-dev libavcodec-dev qtbase5-dev libexpat1-dev libssl-dev \
 zlib1g-dev libc6-dev
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## CLEAN
sudo rm -Rf $DEVDIR/$MKVOSS
sudo rm -Rf $DEVDIR/$MKVBIN

## DOWNLOAD
[ ! -f $DEVDIR/$MKVOSSFILE ] && wget $MKVURL/$MKVOSSFILE
[ ! -f $DEVDIR/$MKVBINFILE ] && wget $MKVURL/$MKVBINFILE

## UNPACK
tar xf $MKVOSSFILE
tar xf $MKVBINFILE

## CONFIGURE
cd $DEVDIR/$MKVOSS
##sed -i "s/av_mallocz_array/av_calloc/g" libffabi/src/ffabi.c
./configure --libdir=/usr/lib/x86_64-linux-gnu

## BUILD
make -j `nproc`

## INSTALL
sudo make install

## MKVBIN INSTALL
cd $DEVDIR/$MKVBIN
sudo make install

sudo ldconfig

## EXIT
exit

## ENJOY
