#!/bin/sh

### Package: nix-install-intel-hybrid-driver
### Version: v20201212.1200
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITREPO=https://github.com/intel
GITTREE=intel-hybrid-driver
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS ]; then
 if [ $INSTALLDEPS = debian ]; then
  sudo apt-get -y install build-essential coreutils libc-bin wget git make \
  libcmrt-dev libtool
 fi
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GET
[ -f $GITTREE\_26.patch ] || wget https://patch-diff.githubusercontent.com/raw/intel/intel-hybrid-driver/pull/26.patch -O $GITTREE\_26.patch

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard
git pull

## CLEAN
rm -Rf tmpbuild

## PATCH
patch -p1 < $DEVDIR/$GITTREE\_26.patch

## CONFIGURE
./autogen.sh
./configure --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu/

## BUILD
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## EXIT
exit

## ENJOY
