#!/bin/sh

### Package: nix-install-cpupower
### Version: v20240825.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# DESTDIR
if [ -z $DESTDIR ]; then
 DESTDIR=/usr
fi
echo "*** DESTDIR selected is $DESTDIR."

# PKGVER
if [ -z $PKGVER ]; then
 PKGVER=6.11-rc5
fi
echo "*** PKGVER selected is $PKGVER."

## VARS
DEVDIR=/tmp/nix-tools
SBINDIR=$DESTDIR/bin
LIBDIR=$DESTDIR/lib/x86_64-linux-gnu
MANDIR=$DESTDIR/share/man
DOCDIR=$DESTDIR/share/doc/cpupower
INCLUDEDIR=$DESTDIR/include

## INSTALLDEPS
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git \
 libpci-dev
fi

## INSTALL
cd $DEVDIR/linux-$PKGVER/tools/power/cpupower
sudo make sbindir=$SBINDIR \
libdir=$LIBDIR \
mandir=$MANDIR \
docdir=$DOCDIR \
includedir=$INCLUDEDIR \
install install-man

## EXIT
exit

## ENJOY
