#!/bin/sh

### Package: nix-install-gtkgreet
### Version: v20210509.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: gtreetd

## OVERRIDES
# NIXTOOLS
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR.\n"

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS.\n"

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH.\n"

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://git.sr.ht
GITREPO=~kennylevinsen
GITTREE=gtkgreet
PKGDIR=$GITTREE\_$GITBRANCH

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git meson
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## CLEAN
rm -Rf tmpbuild

## CONFIGURE
meson tmpbuild -Dprefix=/usr/local -Dbuildtype=release --libdir=/usr/local/lib/x86_64-linux-gnu

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo mkdir -p /usr/local/etc/greetd
sudo install -m 644 -o greeter -g greeter $RESDIR/gtkgreet/sway-config /usr/local/etc/greetd/gtkgreet-sway-config
sudo install -m 644 -o greeter -g greeter $RESDIR/gtkgreet/config.toml /usr/local/etc/greetd/gtkgreet-config.toml
sudo install -m 644 -o greeter -g greeter $RESDIR/gtkgreet/gtkgreet.css /usr/local/etc/greetd/gtkgreet.css
sudo rm -f /usr/local/etc/greetd/config.toml
sudo ln -s /usr/local/etc/greetd/gtkgreet-config.toml /usr/local/etc/greetd/config.toml
sudo ldconfig

## EXIT
exit

## ENJOY
