#!/bin/sh

### Package: nix-install-wlrobs
### Version: v20210109.1200
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: obs

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi

# HGBRANCH
if [ -z $HGBRANCH ]; then
 HGBRANCH=default
fi

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
HGREPO=https://hg.sr.ht/~scoopta
HGTREE=wlrobs
PKGDIR=$HGTREE\_$HGBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS ]; then
 if [ $INSTALLDEPS = debian ]; then
  sudo apt-get -y install build-essential coreutils libc-bin wget mercurial patch meson
 fi
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## HG
echo $HGREPO/$HGTREE
[ -d $PKGDIR ] || hg clone --branch=$HGBRANCH $HGREPO/$HGTREE $PKGDIR
cd $PKGDIR
#git clean -f
#git reset --hard
#git pull

## CLEAN
rm -Rf tmpbuild

## CONFIGURE
meson tmpbuild -Dprefix=/usr/local -Dbuildtype=release --libdir=/usr/local/lib/x86_64-linux-gnu/

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
exit

## ENJOY
