#!/bin/sh

### Package: nix-install-libcamera
### Version: v20200720.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## NIXTOOLS
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
fi

## VARS
DEVDIR=$NIXTOOLSDIR/upstream
GITREPO=git://git.linuxtv.org
GITTREE=libcamera
GITBRANCH=master
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS ]; then
 if [ $INSTALLDEPS = debian ]; then
  sudo apt-get -y install build-essential coreutils libc-bin git meson \
  python3-sphinx libgstreamer-plugins-base1.0-dev libtiff-dev qt5-default \
  libgnutls28-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
  qttools5-dev-tools libboost-dev graphviz
 fi
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard HEAD
git pull

## CLEAN
rm -Rf tmpbuild

## CONFIGURE
meson tmpbuild --buildtype=release --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu \
-Ddocumentation=true -Dgstreamer=enabled -Dv4l2=true
#-Dpipelines="ipu3,simple,uvcvideo,vimc" 

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
exit

## ENJOY
