#!/bin/sh

### Package: nix-install-xfce-panel-plugins
### Version: v20210627.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: xfce-core

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR"

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS"

# GITBRANCH is set in loop

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://gitlab.xfce.org
GITREPO=panel-plugins

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y build-dep xfce4-{battery,clipman,cpufreq,cpugraph,datetime,diskperf,eyes,fsguard}-plugin \
 xfce4-{genmon,indicator,mailwatch,mount,mpc,netload,notes,places,pulseaudio,sensors,smartbookmark}-plugin \
 xfce4-{statusnotifier,systemload,timer,verve,wavelan,weather,whiskermenu,xkb}-plugin
 sudo apt-get -y install build-essential coreutils libc-bin git
fi

# build-deps missing from debian: calculator embed stopwatch time-out windowck generic-slider
# need patching: indicator
# whiskermenu uses cmake and main git branch
# broken: wavelan

## PREP
set -e
mkdir -p $DEVDIR/xfce/$GITREPO
cd $DEVDIR/xfce/$GITREPO

## GIT LOOP
for GITTREE in xfce4-{battery,calculator,clipman,cpufreq,cpugraph,datetime,diskperf,eyes,fsguard,\
genmon,indicator,mailwatch,mount,mpc,netload,notes,places,pulseaudio,sensors,smartbookmark,\
statusnotifier,stopwatch,systemload,time-out,timer,verve,wavelan,weather,whiskermenu,windowck,xkb}-plugin; do
 # VARS
 if [ $GITTREE = xfce4-whiskermenu-plugin ]; then
  GITBRANCH=main
 else
  GITBRANCH=master 
 fi
 
 PKGDIR=$GITTREE\_$GITBRANCH

 # GIT 
 [ -d $PKGDIR ] || git clone --depth=1 --recursive $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
 cd $PKGDIR
 git clean -f
 git reset --hard
 git pull
 git submodule update --init --recursive --depth=1

 # XFCE4-INDICATOR-PLUGIN
 if [ $GITTREE = xfce4-indicator-plugin ]; then
  patch -p1 < $RESDIR/xfce4-indicator-plugin/patches/00_ayatana_configure_git.patch
  patch -p1 < $RESDIR/xfce4-indicator-plugin/patches/01_ayatana_git.patch
 fi

 ## CONFIGURE
 [ -f autogen.sh ] && ./autogen.sh --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu --enable-shared --enable-debug --with-pic

 ## CMAKE CONFIGURE
 #whiskermenu uses cmake
 if [ -f CMakeLists.txt ]; then
  rm -Rf tmpbuild
  mkdir -p tmpbuild
  cd tmpbuild
  cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib/x86_64-linux-gnu -DCMAKE_BUILD_TYPE=Release ..
 fi

 ## BUILD
 make -j `nproc`

 ## INSTALL
 sudo make install
 sudo ldconfig

 ## DONE
 cd $DEVDIR/xfce/$GITREPO
 done

## EXIT
exit

## ENJOY
