#!/bin/sh

### Package: nix-install-mesa
### Version: v20210813.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=main
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# DRIDRIVERS
if [ -z $DRIDRIVERS ];then
 DRIDRIVERS=" "
fi
echo "*** DRIDRIVERS selected is $DRIDRIVERS."

# VULKANDRIVERS
if [ -z $VULKANDRIVERS ];then
 VULKANDRIVERS="amd"
fi
echo "*** VULKANDRIVERS selected is $VULKANDRIVERS."

# GALLIUMDRIVERS
if [ -z $GALLIUMDRIVERS ];then
 GALLIUMDRIVERS="radeonsi"
fi
echo "*** GALLIUMDRIVERS selected is $GALLIUMDRIVERS."

# GITPR
if [ -z $GITPR ];then
 GITPR=10440
fi
echo "*** GITPR selected is $GITPR."

# LLVM
if [ -z $LLVM ];then
 LLVM=enabled
fi
echo "*** LLVM selected is $LLVM.\n"

## VARS
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://gitlab.freedesktop.org
GITREPO=mesa
GITTREE=mesa
PKGDIR=$GITTREE\_$GITBRANCH
GITPRURL=$GITURL
GITPRPATCH=$GITPRURL/$GITREPO/$GITTREE/-/merge_requests/$GITPR.patch

## INSTALLDEPS
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y -t experimental build-dep mesa
 sudo apt-get -y install build-essential coreutils libc-bin git \
 libunwind-dev valgrind libxvmc-dev libxv-dev libxcb-xinput-dev libxcb-damage0-dev \
 libomxil-bellagio-dev libvdpau-dev python3-mako bison byacc flex libxcb-glx0-dev \
 libxcb-dri2-0-dev libxcb-dri3-0-dev
 sudo apt-get -y -t experimental install meson
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## CLEAN
rm -Rf tmpbuild

## GITPR
if [ $GITPR ]; then
 rm -f $DEVDIR/$GITTREE\_$GITPR.patch
 wget $GITPRPATCH -O $DEVDIR/$GITTREE\_$GITPR.patch
 patch -p1 < $DEVDIR/$GITTREE\_$GITPR.patch
fi

## CONFIGURE
meson tmpbuild --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu \
--buildtype=release -Dplatforms=auto -Ddri-drivers=$DRIDRIVERS \
-Dvulkan-drivers=$VULKANDRIVERS -Dgallium-drivers=$GALLIUMDRIVERS \
-Dllvm=$LLVM -Dgallium-opencl=icd -Dopencl-native=true -Dgallium-omx=bellagio

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
exit

# ENJOY
