#!/bin/sh

### Package: nix-install-ffmpeg
### Version: v20210813.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: svt-hevc, x265, x264, vmaf, lensfun

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
# release/4.4 is default for compatibility.
if [ -z $GITBRANCH ]; then
 GITBRANCH=release/4.4
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## OVERRIDES
# Override basic with standard or full
if [ -z $BUILDCONFIG ]; then
 BUILDCONFIG=full
fi
echo "*** BUILDCONFIG selected is $BUILDCONFIG."

## VARS
DATE=`date +%Y%m%d%H%M%S`
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=ffmpeg
GITTREE=ffmpeg
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
  sudo apt-get -y build-dep ffmpeg
  sudo apt-get -y install build-essential coreutils libc-bin wget tar bzip2 patch make \
  libudev-dev libdrm-dev
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard HEAD
git pull
git submodule update --init --depth=1

## UPSTREAM REMOVAL
# --enable-avresample

## BROKEN
# --enable-liblensfun

## CONFIGURE
if [ $BUILDCONFIG = basic ]; then
 echo "\n*** Using basic BUILDCONFIG.\n"
 ./configure --enable-pic --enable-shared --enable-vaapi --enable-libmfx --enable-libvmaf \
 --enable-avfilter --enable-postproc --enable-pthreads --enable-gpl \
 --enable-nonfree --enable-version3 --toolchain=hardened --prefix=/usr/local \
 --libdir=/usr/local/lib/x86_64-linux-gnu --shlibdir=/usr/local/lib/x86_64-linux-gnu
fi
if [ $BUILDCONFIG = standard ]; then
 echo "\n*** Using standard BUILDCONFIG.\n"
 ./configure --enable-pic --enable-shared --enable-vaapi --enable-libmfx --enable-libvmaf \
 --enable-avfilter --enable-postproc --enable-pthreads --enable-gpl \
 --enable-nonfree --enable-version3  --toolchain=hardened --prefix=/usr/local \
 --libdir=/usr/local/lib/x86_64-linux-gnu --shlibdir=/usr/local/lib/x86_64-linux-gnu \
 --enable-avfilter --enable-gcrypt --enable-libass --enable-libbluray --enable-libdav1d \
 --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libmp3lame \
 --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse \
 --enable-librsvg --enable-libspeex --enable-libsrt --enable-libtheora --enable-libtwolame \
 --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 \
 --enable-libxml2 --enable-libxvid --enable-opengl --enable-openssl --enable-libx264
fi
if [ $BUILDCONFIG = full ]; then
 echo "\n*** Using full BUILDCONFIG.\n"
 ./configure --enable-pic --enable-shared --enable-vaapi --enable-libmfx --enable-libvmaf \
 --enable-avfilter --enable-postproc --enable-pthreads --enable-gpl \
 --enable-nonfree --enable-version3 --toolchain=hardened --prefix=/usr/local \
 --libdir=/usr/local/lib/x86_64-linux-gnu --shlibdir=/usr/local/lib/x86_64-linux-gnu \
 --enable-avfilter --enable-gcrypt --enable-libass --enable-libbluray --enable-libdav1d \
 --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libmp3lame \
 --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse \
 --enable-librsvg --enable-libspeex --enable-libsrt --enable-libtheora --enable-libtwolame \
 --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 \
 --enable-libxml2 --enable-libxvid --enable-opengl --enable-openssl --enable-libx264 \
 --enable-ladspa --enable-libaom --enable-libaribb24 --enable-libbs2b --enable-libcaca \
 --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfribidi \
 --enable-libgme --enable-libgsm --enable-libilbc --enable-libjack --enable-libkvazaar \
 --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librubberband \
 --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtesseract --enable-libvidstab \
 --enable-libvo-amrwbenc --enable-libwebp --enable-libzimg --enable-libzmq --enable-libzvbi \
 --enable-lv2 --enable-openal --enable-opencl --enable-chromaprint --enable-frei0r \
 --enable-libiec61883 --enable-libdc1394 --enable-libsvtav1
fi

## CLEAN
make clean

## BUILD
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## EXIT
exit

## ENJOY
