#!/bin/sh

### Package: nix-install-vkmark
### Version: v20210411.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLS
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
fi

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=vkmark
GITTREE=vkmark
PKGDIR=$GITTREE\_$GITBRANCH

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git meson \
 libvulkan-dev libglm-dev libassimp-dev libxcb1-dev libxcb-icccm4-dev \
 libwayland-dev wayland-protocols libdrm-dev libgbm-dev
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard
git pull
git submodule init
git submodule update

## CLEAN
rm -Rf tmpbuild

## CONFIGURE
meson tmpbuild -Dprefix=/usr/local -Dbuildtype=release --libdir=/usr/local/lib/x86_64-linux-gnu \

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
exit

## ENJOY
