#!/bin/sh

### Package: nix-alternatives-llvm
### Version: v20210813.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLS
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR.\n"

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS.\n"

# DEBIANREPO
if [ -z $DEBIANREPO ]; then
 DEBIANREPO=experimental
fi
echo "*** DEBIANREPO selected is $DEBIANREPO.\n"


## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin
 sudo apt-get -y -t $DEBIANREPO install llvm llvm-11 llvm-12 llvm-13 clang clang-11 clang-12 clang-13
fi

## INSTALL
if [ $INSTALLDEPS = debian ]; then
 # LLVM
 sudo rm /usr/bin/llvm-config
 sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-11 11
 sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-12 12
 sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-13 13

 # ALTERNATIVES
 sudo update-alternatives --config llvm-config
fi

## EXIT
exit

## ENJOY

