#!/bin/sh

### Package: nix-install-blueman
### Version: v2021111.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=main
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=blueman-project
GITTREE=blueman
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
# sudo apt-get -y build-dep blueman
 sudo apt-get -y install build-essential coreutils libc-bin meson ninja-build \
 python3-caja nemo-python python3-nautilus cython3 python3
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## CLEAN
rm -Rf tmpbuild

## PATCH
#for file in $RESDIR/blueman/iptables*patch;do patch -p1 < $file;done

## CONFIGURE
PYTHON=/usr/bin/python3 CYTHONEXEC=/usr/bin/cython3 ./autogen.sh --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu \
--exec-prefix=/usr --sysconfdir=/etc --localstatedir=/var \
--with-dhcp-config=/etc/dhcp/dhcpd.conf --with-systemdsystemunitdir=/lib/systemd/system \
--enable-shared --enable-polkit --enable-caja-sendto --enable-nemo-sendto --enable-nautilus-sendto \
--enable-thunar-sendto --enable-settings-integration \
--disable-runtime-deps-check

#meson tmpbuild --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --buildtype=release

#--sysconfdir=/etc
#meson tmpbuild --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu --buildtype=release
#\
#--datadir=/usr/local/share --sysconfdir=/usr/local/etc
#\
#-Ddisable-runtime-deps-check=true -Dwith-dhcp-config=/etc/dhcp/dhcpd.conf \
#-Dwith-systemdsystemunitdir=/lib/systemd/system

## BUILD
#ninja -C tmpbuild
make -j `nproc`

## INSTALL
#sudo ninja -C tmpbuild install
sudo make install
sudo install -m 644 $RESDIR/blueman/blueman.rules /usr/share/polkit-1/rules.d/
sudo install -m 644 $RESDIR/blueman/org.blueman.pkla /var/lib/polkit-1/localauthority/10-vendor.d/
sudo ldconfig

## EXIT
exit

## ENJOY
