#!/bin/sh

### Package: nix-install-amdgpu-top
### Version: v20240611.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=main
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# CC
CC="ccache gcc-14"
CXX="ccache g++-14"
echo "*** CC selected is $CC."
echo "*** CXX selected is $CXX."

# CFLAGSOVERRIDE
if [ -z $CFLAGSOVERRIDE ];then
 CFLAGSOVERRIDE=true
fi
echo "*** CFLAGSOVERRIDE selected is $CFLAGSOVERRIDE."

# CFLAGS
if [ $CFLAGSOVERRIDE = true ]; then
 CFLAGS="-O3 -march=native"
 CPPFLAGS="$CFLAGS"
fi
echo "*** CFLAGS selected is $CFLAGS."

# GITPR
if [ -z $GITPR ]; then
 GITPR=none
fi
echo "*** GITPR selected is $GITPR."

## VARS
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=umio-yasuno
GITTREE=amdgpu_top
PKGDIR=$GITTREE\_$GITBRANCH
GITPRURL=$GITURL
GITPRPATCH=$GITPRURL/$GITREPO/$GITTREE/-/merge_requests/$GITPR.patch

## INSTALLDEPS
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git meson
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## CLEAN
sudo rm -Rf $PKGDIR/tmpbuild

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## GITPR
if [ $GITPR != none ]; then
 rm -f $DEVDIR/$GITTREE\_$GITPR.patch
 wget $GITPRPATCH -O $DEVDIR/$GITTREE\_$GITPR.patch
 patch -p1 < $DEVDIR/$GITTREE\_$GITPR.patch
fi

## CONFIGURE
cargo install --locked --path .

## BUILD
#ninja -C tmpbuild

## INSTALL
#sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
exit

# ENJOY
