#!/bin/sh

### Package: nix-install-handbrake
### Version: v20211128.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: pipewire

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
# Upstream is master, Stable is 1.5.x
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
DESTDIR=/usr/local
MULTILIBDIR=`gcc -dumpmachine`
GITURL=https://github.com
GITREPO=handbrake
GITTREE=handbrake
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git patch
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## CLEAN
sudo rm -Rf $PKGDIR/tmpbuild

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## PATCH
#patch -p0 make/include/main.defs < $RESDIR/handbrake/handbrake_git_main.defs.diff
#patch -p0 < $RESDIR/handbrake/handbrake_module.defs.diff

## CONFIGURE
./configure --prefix=$DESTDIR --libdir=$DESTDIR/lib/$MULTILIBDIR \
--enable-gtk3 --enable-x265 --enable-numa --enable-fdk-aac --enable-nvenc \
--enable-qsv --enable-vce

## BUILD
cd build
make -j `nproc`

## INSTALL
sudo make install
[ -f $DESTDIR/bin/handbrake-gtk ] || sudo ln -s $DESTDIR/bin/ghb $DESTDIR/bin/handbrake-gtk
sudo ldconfig

## EXIT
exit

## ENJOY
