#!/bin/sh

### Package: nix-install-iniparser
### Version: v20240504.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# DESTDIR
if [ -z $DESTDIR ]; then
 DESTDIR=/usr/local
fi
echo "*** DESTDIR selected is $DESTDIR."

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=ndevilla
GITTREE=iniparser
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git meson
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## CLEAN
sudo rm -Rf $PKGDIR/tmpbuild

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --depth=1

## CONFIGURE
if [ DESTDIR = /usr/local ]; then
 sed -i 's/\/usr/\/usr\/local/g' Makefile
 sed -i 's/\/usr/\/usr\/local/g' iniparser.pc
fi

## BUILD
make -j `nproc`

## INSTALL
sudo install -D iniparser.pc $DESTDIR/lib/x86_64-linux-gnu/pkgconfig/iniparser.pc
sudo install -D src/iniparser.h $DESTDIR/include/iniparser.h
sudo install -D src/dictionary.h $DESTDIR/include/dictionary.h
sudo install -D libiniparser.a $DESTDIR/lib/x86_64-linux-gnu/libiniparser.a
sudo install -D libiniparser.so.1 $DESTDIR/lib/x86_64-linux-gnu/libiniparser.so.1
sudo ln -f -s $DESTDIR/lib/x86_64-linux-gnu/libiniparser.so.1 \
$DESTDIR/lib/x86_64-linux-gnu/libiniparser.so

sudo ldconfig

## EXIT
exit

## ENJOY
