#!/bin/sh

### Package: nix-install-wlgreet
### Version: v20210510.1600
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: greetd

## OVERRIDES
# NIXTOOLS
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR.\n"

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS.\n"

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH.\n"

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://git.sr.ht
GITREPO=~kennylevinsen
GITTREE=wlgreet
PKGDIR=$GITTREE\_$GITBRANCH

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git meson cargo
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## BUILD
cargo build --release

## INSTALL
sudo mkdir -p /usr/local/bin
sudo install -m 755 target/release/wlgreet /usr/local/bin/wlgreet
sudo mkdir -p /usr/local/etc/greetd
sudo install -m 644 -o greeter -g greeter $RESDIR/wlgreet/sway-config /usr/local/etc/greetd/wlgreet-sway-config
sudo install -m 644 -o greeter -g greeter $RESDIR/wlgreet/config.toml /usr/local/etc/greetd/wlgreet-config.toml
sudo rm -f /usr/local/etc/greetd/config.toml
sudo ln -s /usr/local/etc/greetd/wlgreet-config.toml /usr/local/etc/greetd/config.toml

## EXIT
exit

## ENJOY
