#!/bin/sh

### Package: nix-install-pipewire
### Version: v20210813.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: libcamera

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## VARS
DEVDIR=$NIXTOOLSDIR/upstream
GITREPO=https://gitlab.freedesktop.org/pipewire
GITTREE=pipewire
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y build-dep pipewire
 sudo apt-get -y install build-essential coreutils libc-bin git meson \
 libbluetooth-dev libsdl2-dev libjack-jackd2-dev libcamera-dev \
 libldacbt-enc-dev libldacbt-abr-dev libopenaptx-dev libfdk-aac-dev \
 libavcodec-dev
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard HEAD
git pull
git submodule update --init --recursive --depth=1

## CLEAN
rm -Rf tmpbuild

## CONFIGURE
meson tmpbuild --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu --buildtype=release \
-Ddocs=enabled -Dffmpeg=enabled -Dvolume=enabled -Dlibcamera=enabled  -Dsystemd-system-service=enabled \
-Djack-devel=true -Dvulkan=enabled

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
[ -f /usr/local/share/pipewire/media-session.d/with-alsa ] || \
sudo touch /usr/local/share/pipewire/media-session.d/with-alsa
sudo rm -f /etc/alsa/conf.d/50-pipewire.conf
sudo ln -s /usr/local/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d/50-pipewire.conf
sudo rm -f /etc/alsa/conf.d/99-pipewire-default.conf
sudo ln -s /usr/local/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d/99-pipewire-default.conf
sudo ldconfig

## USER CONFIG
systemctl --user enable --now pipewire.service pipewire.socket pipewire-media-session.service \
pipewire-pulse.service pipewire-pulse.socket
systemctl --user stop --now pipewire.service pipewire.socket pipewire-media-session.service \
pipewire-pulse.service pipewire-pulse.socket
systemctl --user start --now pipewire.service pipewire.socket pipewire-media-session.service \
pipewire-pulse.service pipewire-pulse.socket
systemctl --user daemon-reload

## EXIT
exit

## ENJOY
