#!/bin/sh

### Package: nix-config-mozilla
### Version: v20240404.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR.\n"

## VARS
DATE=`date +%Y%m%d%H%M%S`
RESDIR=$NIXTOOLSDIR/resources

## OVERRIDES
# Override debian.
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS.\n"

## DEBIAN CONFIG
if [ $INSTALLDEPS = debian ]; then
 ## APTCONFIG
 sudo install -d -m 0755 /etc/apt/keyrings
 wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
 echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null

 ## APT UPDATE
 sudo apt-get -y update
fi

## EXIT
exit

## ENJOY
