#!/bin/sh

### Package: nix-install-spirv-llvm
### Version: v20240504.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
# Upstream is "main"
if [ -z $GITBRANCH ]; then
 GITBRANCH=main
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# DESTDIR
if [ -z $DESTDIR ]; then
 DESTDIR=/usr/local
fi
echo "*** DESTDIR selected is $DESTDIR."

# LLVMVER
if [ -z $LLVMVER ]; then
 LLVMVER=19.1
fi
echo "*** LLVMVER selected is $LLVMVER."

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=khronosgroup
GITTREE=spirv-llvm-translator
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git make cmake
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## CLEAN
sudo rm -Rf $PKGDIR/tmpbuild

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## CONFIGURE
mkdir tmpbuild
cd tmpbuild
cmake -DCMAKE_INSTALL_PREFIX=$DESTDIR -DCMAKE_INSTALL_LIBDIR=$DESTDIR/lib/x86_64-linux-gnu \
-DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
-DLLVM_EXTERNAL_PROJECTS="SPIRV-Headers" -DLLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR=$DESTDIR/include/spirv \
-DLLVM_DIR=/usr/include/llvm-$LLVMVER -DBASE_LLVM_VERSION=$LLVMVER ..

## BUILD
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## EXIT
exit

## ENJOY
