#!/bin/sh

### Package: nix-install-greetd
### Version: v20210509.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLS
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR.\n"

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS.\n"

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH.\n"

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://git.sr.ht
GITREPO=~kennylevinsen
GITTREE=greetd
PKGDIR=$GITTREE\_$GITBRANCH

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git meson cargo
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## BUILD
cargo build --release

## MAN
cd man
for file in *.scd;do scdoc < $file > $file.roff;done
cd ..

## INSTALL
sudo mkdir -p /usr/local/bin
sudo install -m 755 target/release/greetd /usr/local/bin/
sudo install -m 755 target/release/agreety /usr/local/bin/
sudo mkdir -p /usr/local/share/man/man1
sudo mkdir -p /usr/local/share/man/man5
sudo mkdir -p /usr/local/share/man/man7
sudo install -m 755 man/agreety-1.scd.roff /usr/local/share/man/man1/agreety.1
sudo install -m 755 man/greetd-1.scd.roff /usr/local/share/man/man1/greetd.1
sudo install -m 755 man/greetd-5.scd.roff /usr/local/share/man/man5/greetd.5
sudo install -m 755 man/greetd-ipc-7.scd.roff /usr/local/share/man/man7/greetd-ipc.7
sudo mkdir -p /usr/local/etc/systemd/system
sudo install -m 755 greetd.service /usr/local/etc/systemd/system/greetd.service
grep -qw ^greeter /etc/group || sudo useradd -M -G video greeter
sudo mkdir -p /usr/local/etc/greetd
sudo install -m 644 -o greeter -g greeter config.toml /usr/local/etc/greetd/greetd-config.toml
[ -f /usr/local/etc/greetd/environments ] || sudo install -m 644 -o greeter -g greeter $RESDIR/greetd/environments /usr/local/etc/greetd/environments
[ -L /usr/local/etc/greetd/config.toml ] || sudo ln -s /usr/local/etc/greetd/greetd-config.toml /usr/local/etc/greetd/config.toml
[ -L /etc/greetd ] || sudo ln -s /usr/local/etc/greetd /etc/greetd
[ -L /etc/systemd/system/greetd.service ] || sudo ln -s /usr/local/etc/systemd/system/greetd.service /etc/systemd/system/greetd.service
sudo mkdir -p /usr/local/etc/pam.d
sudo install -m 644 $RESDIR/greetd/pam /usr/local/etc/pam.d/greetd

## INSTRUCTIONS
echo "Enable greetd by: systemctl enable greetd && systemctl start greetd. Note: Your current session will be disrupted."

## EXIT
exit

## ENJOY
