#!/bin/sh

### Package: nix-install-imv
### Version: v20210912.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLSDIR
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## VARS
RESDIR=$NIXTOOLSDIR/resources
DEVDIR=$NIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=exec64
GITTREE=imv
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git make meson \
 asciidoc-base asciidoc-common libcmocka-dev libfreeimage-dev \
 libturbojpeg0-dev libxkbcommon-x11-dev
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## CLEAN
sudo rm -Rf $PKGDIR/tmpbuild

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## CONFIGURE
meson tmpbuild --prefix=/usr/local --libdir=/usr/local/lib/x86_64-linux-gnu --buildtype=release

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
exit

## ENJOY
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
0 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,681 kB of archives.
After this operation, 6,083 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
