#!/bin/sh

### Package: nix-alternatives-gcc
### Version: v20210813.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# NIXTOOLS
if [ -z $NIXTOOLSDIR ]; then
 NIXTOOLSDIR="`pwd`"
 PATH=$NIXTOOLSDIR:$PATH
fi
echo "*** NIXTOOLSDIR selected is $NIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# DEBIANREPO
if [ -z $DEBIANREPO ]; then
 DEBIANREPO=unstable
fi
echo "*** DEBIANREPO selected is $DEBIANREPO."

# GCCVER
if [ -z $GCCVER ]; then
 GCCVER=11
fi
echo "*** GCCVER selected is $GCCVER."

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y install build-essential coreutils libc-bin
 sudo apt-get -y install -t $DEBIANREPO gcc gcc-$GCCVER g++ g++-$GCCVER
fi

## INSTALL
if [ $INSTALLDEPS = debian ]; then
 # GCC
 sudo rm /usr/bin/gcc
 sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
 sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11

 # G++
 sudo rm /usr/bin/g++
 sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
 sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 11

 # ALTERNATIVES
 sudo update-alternatives --config gcc
 sudo update-alternatives --config g++
fi

## EXIT
exit

## ENJOY
