## libva
export LIBVA_DRIVER_NAME=i965

## wayland
#export GDK_BACKEND=wayland
#export CLUTTER_BACKEND=wayland
#export XDG_CURRENT_DESKTOP=sway

## firefox
export MOZ_ENABLE_WAYLAND=1
#export MOZ_DBUS_REMOTE=1

## gstreamer
#export GST_VAAPI_ALL_DRIVERS=1
#export GST_GL_WINDOW=wayland

## dotnet
export DOTNET_ROOT=/usr/local/dotnet

## PATH
export PATH=~/bin:~/go/bin:/usr/local/dotnet:$PATH
