#!/bin/sh

### Name: sway-run
### Version: v20211111.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: sway

## ENVIRONMENTAL VARIABLES

# WAYLAND
export XDG_SESSION_TYPE=wayland
export CLUTTER_BACKEND=wayland
export QT_QPA_PLATFORM=wayland-egl
export ECORE_EVAS_ENGINE=wayland-egl
export ELM_ENGINE=wayland_egl
export SDL_VIDEODRIVER=wayland

# WLROOTS
#export WLR_RENDERER=vulkan

# SWAY
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

# MISC
export MOZ_ENABLE_WAYLAND=1
export _JAVA_AWT_WM_NONREPARENTING=1
export NO_AT_BRIDGE=1

## EXECUTE

systemd-cat --identifier=sway sway $@;

## EXIT
exit

## ENJOY
